// Mapa chave→componente para os ícones do NAV_ICONS declarados na registry
// (src/lib/nav/routes.ts). A registry fica dados puros (serializável, testável
// em node sem DOM); só este módulo conhece lucide.
import {
  BarChart3,
  Bot,
  Box,
  CalendarDays,
  ClipboardList,
  DollarSign,
  Fingerprint,
  FlaskConical,
  FileImage,
  FileText,
  Globe,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LockKeyhole,
  Megaphone,
  MessagesSquare,
  Network,
  Package,
  Palette,
  PenTool,
  Rocket,
  Ruler,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Table,
  Truck,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon } from "./routes";

export const NAV_ICON_COMPONENTS: Record<NavIcon, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  workflow: Workflow,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  palette: Palette,
  "file-image": FileImage,
  "layout-template": LayoutTemplate,
  table: Table,
  layers: Layers,
  fingerprint: Fingerprint,
  scissors: Scissors,
  "flask-conical": FlaskConical,
  "file-text": FileText,
  ruler: Ruler,
  pen: PenTool,
  package: Package,
  network: Network,
  calendar: CalendarDays,
  box: Box,
  truck: Truck,
  store: Store,
  megaphone: Megaphone,
  shopping: ShoppingBag,
  rocket: Rocket,
  bot: Bot,
  chart: BarChart3,
  globe: Globe,
  lock: LockKeyhole,
  users: Users,
  clipboard: ClipboardList,
  "messages-square": MessagesSquare,
  dollar: DollarSign,
};
