/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTechSheetRouteImport } from './routes/_authenticated.tech-sheet'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated.suppliers'
import { Route as AuthenticatedShowroomRouteImport } from './routes/_authenticated.showroom'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated.research'
import { Route as AuthenticatedReferencesRouteImport } from './routes/_authenticated.references'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated.quality'
import { Route as AuthenticatedPrototypesRouteImport } from './routes/_authenticated.prototypes'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated.production'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated.planner'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated.marketing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated.inventory'
import { Route as AuthenticatedInfluencersRouteImport } from './routes/_authenticated.influencers'
import { Route as AuthenticatedFinancialRouteImport } from './routes/_authenticated.financial'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated.feed'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated.digital-twin'
import { Route as AuthenticatedDevelopmentRouteImport } from './routes/_authenticated.development'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCommercialRouteImport } from './routes/_authenticated.commercial'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated.collections'
import { Route as AuthenticatedCadRouteImport } from './routes/_authenticated.cad'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAiCenterRouteImport } from './routes/_authenticated.ai-center'
import { Route as AuthenticatedAiAgentsRouteImport } from './routes/_authenticated.ai-agents'
import { Route as AuthenticatedProductionTodayRouteImport } from './routes/_authenticated.production.today'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTechSheetRoute = AuthenticatedTechSheetRouteImport.update({
  id: '/tech-sheet',
  path: '/tech-sheet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShowroomRoute = AuthenticatedShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferencesRoute = AuthenticatedReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrototypesRoute = AuthenticatedPrototypesRouteImport.update({
  id: '/prototypes',
  path: '/prototypes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInfluencersRoute =
  AuthenticatedInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialRoute = AuthenticatedFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevelopmentRoute =
  AuthenticatedDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommercialRoute = AuthenticatedCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadRoute = AuthenticatedCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiCenterRoute = AuthenticatedAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAgentsRoute = AuthenticatedAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionTodayRoute =
  AuthenticatedProductionTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/ai-center': typeof AuthenticatedAiCenterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/cad': typeof AuthenticatedCadRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/influencers': typeof AuthenticatedInfluencersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/prototypes': typeof AuthenticatedPrototypesRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/research': typeof AuthenticatedResearchRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/showroom': typeof AuthenticatedShowroomRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tech-sheet': typeof AuthenticatedTechSheetRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/production/today': typeof AuthenticatedProductionTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/ai-center': typeof AuthenticatedAiCenterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/cad': typeof AuthenticatedCadRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/influencers': typeof AuthenticatedInfluencersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/prototypes': typeof AuthenticatedPrototypesRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/references': typeof AuthenticatedReferencesRoute
  '/research': typeof AuthenticatedResearchRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/showroom': typeof AuthenticatedShowroomRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tech-sheet': typeof AuthenticatedTechSheetRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/production/today': typeof AuthenticatedProductionTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai-agents': typeof AuthenticatedAiAgentsRoute
  '/_authenticated/ai-center': typeof AuthenticatedAiCenterRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/cad': typeof AuthenticatedCadRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/commercial': typeof AuthenticatedCommercialRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/development': typeof AuthenticatedDevelopmentRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/financial': typeof AuthenticatedFinancialRoute
  '/_authenticated/influencers': typeof AuthenticatedInfluencersRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/prototypes': typeof AuthenticatedPrototypesRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/references': typeof AuthenticatedReferencesRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/showroom': typeof AuthenticatedShowroomRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/tech-sheet': typeof AuthenticatedTechSheetRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/production/today': typeof AuthenticatedProductionTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/login'
    | '/sitemap.xml'
    | '/ai-agents'
    | '/ai-center'
    | '/analytics'
    | '/cad'
    | '/collections'
    | '/commercial'
    | '/dashboard'
    | '/development'
    | '/digital-twin'
    | '/feed'
    | '/financial'
    | '/influencers'
    | '/inventory'
    | '/marketing'
    | '/planner'
    | '/production'
    | '/prototypes'
    | '/quality'
    | '/references'
    | '/research'
    | '/security'
    | '/showroom'
    | '/suppliers'
    | '/tech-sheet'
    | '/admin/users'
    | '/production/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/login'
    | '/sitemap.xml'
    | '/ai-agents'
    | '/ai-center'
    | '/analytics'
    | '/cad'
    | '/collections'
    | '/commercial'
    | '/dashboard'
    | '/development'
    | '/digital-twin'
    | '/feed'
    | '/financial'
    | '/influencers'
    | '/inventory'
    | '/marketing'
    | '/planner'
    | '/production'
    | '/prototypes'
    | '/quality'
    | '/references'
    | '/research'
    | '/security'
    | '/showroom'
    | '/suppliers'
    | '/tech-sheet'
    | '/admin/users'
    | '/production/today'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/audit'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/ai-agents'
    | '/_authenticated/ai-center'
    | '/_authenticated/analytics'
    | '/_authenticated/cad'
    | '/_authenticated/collections'
    | '/_authenticated/commercial'
    | '/_authenticated/dashboard'
    | '/_authenticated/development'
    | '/_authenticated/digital-twin'
    | '/_authenticated/feed'
    | '/_authenticated/financial'
    | '/_authenticated/influencers'
    | '/_authenticated/inventory'
    | '/_authenticated/marketing'
    | '/_authenticated/planner'
    | '/_authenticated/production'
    | '/_authenticated/prototypes'
    | '/_authenticated/quality'
    | '/_authenticated/references'
    | '/_authenticated/research'
    | '/_authenticated/security'
    | '/_authenticated/showroom'
    | '/_authenticated/suppliers'
    | '/_authenticated/tech-sheet'
    | '/_authenticated/admin/users'
    | '/_authenticated/production/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tech-sheet': {
      id: '/_authenticated/tech-sheet'
      path: '/tech-sheet'
      fullPath: '/tech-sheet'
      preLoaderRoute: typeof AuthenticatedTechSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showroom': {
      id: '/_authenticated/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof AuthenticatedShowroomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/references': {
      id: '/_authenticated/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof AuthenticatedReferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prototypes': {
      id: '/_authenticated/prototypes'
      path: '/prototypes'
      fullPath: '/prototypes'
      preLoaderRoute: typeof AuthenticatedPrototypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/influencers': {
      id: '/_authenticated/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof AuthenticatedInfluencersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial': {
      id: '/_authenticated/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AuthenticatedFinancialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/development': {
      id: '/_authenticated/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof AuthenticatedDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commercial': {
      id: '/_authenticated/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof AuthenticatedCommercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cad': {
      id: '/_authenticated/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedCadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-center': {
      id: '/_authenticated/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AuthenticatedAiCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-agents': {
      id: '/_authenticated/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AuthenticatedAiAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production/today': {
      id: '/_authenticated/production/today'
      path: '/today'
      fullPath: '/production/today'
      preLoaderRoute: typeof AuthenticatedProductionTodayRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionTodayRoute: typeof AuthenticatedProductionTodayRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionTodayRoute: AuthenticatedProductionTodayRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiAgentsRoute: typeof AuthenticatedAiAgentsRoute
  AuthenticatedAiCenterRoute: typeof AuthenticatedAiCenterRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCadRoute: typeof AuthenticatedCadRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCommercialRoute: typeof AuthenticatedCommercialRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevelopmentRoute: typeof AuthenticatedDevelopmentRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFinancialRoute: typeof AuthenticatedFinancialRoute
  AuthenticatedInfluencersRoute: typeof AuthenticatedInfluencersRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedPrototypesRoute: typeof AuthenticatedPrototypesRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReferencesRoute: typeof AuthenticatedReferencesRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedShowroomRoute: typeof AuthenticatedShowroomRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTechSheetRoute: typeof AuthenticatedTechSheetRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAgentsRoute: AuthenticatedAiAgentsRoute,
  AuthenticatedAiCenterRoute: AuthenticatedAiCenterRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCadRoute: AuthenticatedCadRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCommercialRoute: AuthenticatedCommercialRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevelopmentRoute: AuthenticatedDevelopmentRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFinancialRoute: AuthenticatedFinancialRoute,
  AuthenticatedInfluencersRoute: AuthenticatedInfluencersRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedPrototypesRoute: AuthenticatedPrototypesRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReferencesRoute: AuthenticatedReferencesRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedShowroomRoute: AuthenticatedShowroomRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTechSheetRoute: AuthenticatedTechSheetRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
